window._layerConfigs = [
    {
        "i_id": 152,
        "d_firstDpi": "0.703125",
        "i_minLevel": 1,
        "i_createUserId": 1005,
        "I_IMGLEVEL_INOLMAP": 15,
        "c_sid": 1845,
        "capability": {
            "i_isLoadIn3D": 1,
            "i_geoQuery": "",
            "c_serverType": "",
            "i_edit": "",
            "i_select": "",
            "c_geoType": "",
            "i_hasTbEntity": "null",
            "i_sorption": "",
            "c_serverUrl": "",
            "i_add": ""
        },
        "i_maxLevel": 19,
        "c_layerName": "2021版影像",
        "c_dataName": "2021版影像",
        "c_imgTime": "YNYBYX2021",
        "c_path": "/onemap21/rest/wmts?tk=5B4C7B8BF2E78640",
        "c_dataServiceParam": "",
        "c_source": "ZY3",
        "c_origin": "[-180, 90]",
        "c_group": "",
        "c_style": "",
        "c_extent": "",
        "c_zqCode": "200000",
        "c_zqName": "全国",
        "i_visible": 0,
        "i_delete": "",
        "c_ogc": "WMTS",
        "d_opacity": 1,
        "i_swipe": 1,
        "c_metadata": "",
        "c_url": "http://yxsj.stgz.org.cn",
        "C_APPID": "LDT",
        "c_type": "TILE_SERVICE",
        "c_serviceCode": "",
        "c_ztName": "测绘影像",
        "i_zIndex": 608,
        "i_isUserData": "",
        "c_parameter": "{\"style\":\"default\",\"layer\":\"satImage\",\"matrixSet\":\"satImage\"}                                                                                                                                                                                                  "
    },
    {
        "i_id": 51818,
        "d_firstDpi": "0.703125",
        "i_minLevel": 1,
        "i_createUserId": 116,
        "I_IMGLEVEL_INOLMAP": "",
        "c_sid": 2,
        "capability": {
            "i_isLoadIn3D": "",
            "i_geoQuery": "",
            "c_serverType": "",
            "i_edit": 0,
            "i_select": 0,
            "c_geoType": "",
            "i_hasTbEntity": "0",
            "i_sorption": "",
            "c_serverUrl": "",
            "i_add": 0
        },
        "i_maxLevel": 18,
        "c_layerName": "天地图政区标注",
        "c_dataName": "天地图政区标注",
        "c_imgTime": "",
        "c_path": "/DataServer?T=cva_c&x={x}&y={y}&l={z}&tk=643be9d1157982875dedbf77dcebf67c",
        "c_dataServiceParam": "",
        "c_source": "TDT",
        "c_origin": "[-180, 90]",
        "c_group": "",
        "c_style": "",
        "c_extent": "",
        "c_zqCode": "200000",
        "c_zqName": "全国",
        "i_visible": 0,
        "i_delete": 0,
        "c_ogc": "XYZ",
        "d_opacity": 1,
        "i_swipe": 0,
        "c_metadata": "",
        "c_url": "http://t{0-7}.tianditu.gov.cn",
        "C_APPID": "LDT",
        "c_type": "TILE_SERVICE",
        "c_serviceCode": "",
        "c_ztName": "天地图底图",
        "i_zIndex": 6001,
        "i_isUserData": 0,
        "c_parameter": ""
    },
    {
        "i_id": 51812,
        "d_firstDpi": "0.703125",
        "i_minLevel": 1,
        "i_createUserId": 1167,
        "I_IMGLEVEL_INOLMAP": "",
        "c_sid": 1,
        "capability": {
            "i_isLoadIn3D": "",
            "i_geoQuery": "",
            "c_serverType": "",
            "i_edit": "",
            "i_select": "",
            "c_geoType": "",
            "i_hasTbEntity": "0",
            "i_sorption": "",
            "c_serverUrl": "",
            "i_add": ""
        },
        "i_maxLevel": 18,
        "c_layerName": "天地图政区",
        "c_dataName": "天地图政区",
        "c_imgTime": "",
        "c_path": "/DataServer?T=vec_c&x={x}&y={y}&l={z}&tk=643be9d1157982875dedbf77dcebf67c",
        "c_dataServiceParam": "",
        "c_source": "TDT",
        "c_origin": "[-180, 90]",
        "c_group": "",
        "c_style": "",
        "c_extent": "",
        "c_zqCode": "200000",
        "c_zqName": "全国",
        "i_visible": 1,
        "i_delete": "",
        "c_ogc": "XYZ",
        "d_opacity": 1,
        "i_swipe": "",
        "c_metadata": "",
        "c_url": "http://t{0-7}.tianditu.gov.cn",
        "C_APPID": "LDT",
        "c_type": "TILE_SERVICE",
        "c_serviceCode": "",
        "c_ztName": "天地图底图",
        "i_zIndex": 503,
        "i_isUserData": 0,
        "c_parameter": ""
    }
]